apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samplewebapp
  name: samplewebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      labels:
        app: samplewebapp
    spec:
      containers:
      - image: arcbc5524.azurecr.io/samplewebapp:v1
        name: samplewebapp