# Default values for ibis-digitaalmeten-spa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
host: "failure.com"

replicaCount: 2

image:
  repository: mcr.microsoft.com/dotnet/samples
  tag: aspnetapp
  pullPolicy: IfNotPresent

service:
  port: 80

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

nodeSelector:

tolerations:
  #- key: "runTime"
  #  operator: "Equal"
  #  value: "windows"
  #  effect: "NoSchedule"

affinity: {}